version: '3'

services:
  first_db:
    image: postgres:alpine
    environment:
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=nestintro_db_1
    ports:
      - 5431:5432

  second_db:
    image: postgres:alpine
    environment: 
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=nestintro_db_2
    ports:
      - 5432:5432
