version: '3'

services:
  school_db:
    image: postgres
    environment:
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=nestschool
    ports:
      - 5432:5432
